# ============================================================
# STAGE 20.2 - ML MODEL TRAINING
# stage20/train_model.py
# ============================================================

import os
import json
import warnings

import joblib
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
)

warnings.filterwarnings("ignore")


# ============================================================
# PATHS
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

DATA_DIR = os.path.join(
    BASE_DIR,
    "data",
    "stage20"
)

MODEL_DIR = os.path.join(
    BASE_DIR,
    "models"
)

TRAINING_FILE = os.path.join(
    DATA_DIR,
    "stage20_training_data.csv"
)

MODEL_FILE = os.path.join(
    MODEL_DIR,
    "stock_classifier.pkl"
)

FEATURE_FILE = os.path.join(
    MODEL_DIR,
    "feature_columns.json"
)

METRICS_FILE = os.path.join(
    MODEL_DIR,
    "training_metrics.json"
)


# ============================================================
# CONFIGURATION
# ============================================================

TEST_SIZE = 0.20

RANDOM_STATE = 42

MIN_ROWS_REQUIRED = 30


# ============================================================
# FEATURE COLUMNS
# ============================================================

# These are the numerical market/technical features
# generated by Stage 20 Feature Builder.

FEATURE_COLUMNS = [
    "close",
    "volume",

    "return_1d",
    "return_5d",
    "return_10d",

    "sma20",
    "sma120",
    "sma20_sma120_ratio",

    "rsi",

    "etq_5m",
    "etq_20m",
    "etq_60m",

    "high_low_range",
    "open_close_range",

    "volatility_10d",
    "volatility_20d",

    "volume_change",
    "volume_ratio",

    "momentum_5d",
    "momentum_20d",
]


# ============================================================
# LOAD DATA
# ============================================================

def load_training_data():

    print()
    print("=" * 80)
    print("LOADING STAGE 20 TRAINING DATA")
    print("=" * 80)

    if not os.path.exists(TRAINING_FILE):

        raise FileNotFoundError(
            f"Training file not found:\n"
            f"{TRAINING_FILE}"
        )

    df = pd.read_csv(
        TRAINING_FILE
    )

    print(
        f"Training file: {TRAINING_FILE}"
    )

    print(
        f"Rows loaded: {len(df)}"
    )

    print(
        f"Columns loaded: {len(df.columns)}"
    )

    if len(df) < MIN_ROWS_REQUIRED:

        raise ValueError(
            f"Not enough training rows. "
            f"Required at least {MIN_ROWS_REQUIRED}, "
            f"but only {len(df)} available."
        )

    return df


# ============================================================
# VALIDATE COLUMNS
# ============================================================

def validate_columns(df):

    print()
    print("=" * 80)
    print("VALIDATING TRAINING COLUMNS")
    print("=" * 80)

    required_columns = (
        FEATURE_COLUMNS
        + ["target"]
    )

    missing_columns = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:

        print(
            "Missing columns:"
        )

        for column in missing_columns:

            print(
                f"  - {column}"
            )

        raise ValueError(
            "Stage 20 training data does not "
            "contain all required columns."
        )

    print(
        "All required feature columns found."
    )

    print(
        f"Features available: "
        f"{len(FEATURE_COLUMNS)}"
    )

    return True


# ============================================================
# CLEAN DATA
# ============================================================

def clean_data(df):

    print()
    print("=" * 80)
    print("CLEANING TRAINING DATA")
    print("=" * 80)

    working_df = df.copy()

    # --------------------------------------------------------
    # Sort chronologically if date exists
    # --------------------------------------------------------

    if "date" in working_df.columns:

        working_df["date"] = pd.to_datetime(
            working_df["date"],
            errors="coerce"
        )

        working_df = working_df.sort_values(
            "date"
        )

    # --------------------------------------------------------
    # Convert features to numeric
    # --------------------------------------------------------

    for column in FEATURE_COLUMNS:

        working_df[column] = pd.to_numeric(
            working_df[column],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Convert target
    # --------------------------------------------------------

    working_df["target"] = pd.to_numeric(
        working_df["target"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Replace infinite values
    # --------------------------------------------------------

    working_df = working_df.replace(
        [np.inf, -np.inf],
        np.nan
    )

    before = len(working_df)

    # --------------------------------------------------------
    # Remove missing feature/target rows
    # --------------------------------------------------------

    working_df = working_df.dropna(
        subset=(
            FEATURE_COLUMNS
            + ["target"]
        )
    )

    # --------------------------------------------------------
    # Target must be binary
    # --------------------------------------------------------

    working_df = working_df[
        working_df["target"].isin(
            [0, 1]
        )
    ]

    # --------------------------------------------------------
    # Convert target to integer
    # --------------------------------------------------------

    working_df["target"] = (
        working_df["target"]
        .astype(int)
    )

    after = len(working_df)

    print(
        f"Rows before cleaning : {before}"
    )

    print(
        f"Rows after cleaning  : {after}"
    )

    print(
        f"Rows removed         : "
        f"{before - after}"
    )

    if after < MIN_ROWS_REQUIRED:

        raise ValueError(
            "Not enough clean rows available "
            "for model training."
        )

    # --------------------------------------------------------
    # Target distribution
    # --------------------------------------------------------

    target_counts = (
        working_df["target"]
        .value_counts()
        .sort_index()
    )

    print()
    print(
        "Target distribution:"
    )

    for target_value, count in target_counts.items():

        print(
            f"  Target {target_value}: "
            f"{count}"
        )

    # --------------------------------------------------------
    # Both classes required
    # --------------------------------------------------------

    unique_targets = (
        working_df["target"]
        .nunique()
    )

    if unique_targets < 2:

        raise ValueError(
            "Training data contains only one "
            "target class. Need both 0 and 1."
        )

    return working_df.reset_index(
        drop=True
    )


# ============================================================
# PREPARE FEATURES / TARGET
# ============================================================

def prepare_xy(df):

    print()
    print("=" * 80)
    print("PREPARING FEATURES")
    print("=" * 80)

    X = df[
        FEATURE_COLUMNS
    ].copy()

    y = df[
        "target"
    ].copy()

    print(
        f"X shape: {X.shape}"
    )

    print(
        f"y shape: {y.shape}"
    )

    return X, y


# ============================================================
# CHRONOLOGICAL TRAIN / TEST SPLIT
# ============================================================

def chronological_split(X, y):

    print()
    print("=" * 80)
    print("CHRONOLOGICAL TRAIN / TEST SPLIT")
    print("=" * 80)

    total_rows = len(X)

    split_index = int(
        total_rows
        * (1 - TEST_SIZE)
    )

    if split_index <= 0:

        raise ValueError(
            "Invalid training split."
        )

    if split_index >= total_rows:

        split_index = total_rows - 1

    X_train = X.iloc[
        :split_index
    ].copy()

    X_test = X.iloc[
        split_index:
    ].copy()

    y_train = y.iloc[
        :split_index
    ].copy()

    y_test = y.iloc[
        split_index:
    ].copy()

    print(
        f"Total rows     : {total_rows}"
    )

    print(
        f"Training rows  : {len(X_train)}"
    )

    print(
        f"Testing rows   : {len(X_test)}"
    )

    print(
        f"Training range : "
        f"{len(X_train) / total_rows:.2%}"
    )

    print(
        f"Testing range  : "
        f"{len(X_test) / total_rows:.2%}"
    )

    # --------------------------------------------------------
    # Check both target classes
    # --------------------------------------------------------

    if y_train.nunique() < 2:

        raise ValueError(
            "Training split contains only one "
            "target class."
        )

    if y_test.nunique() < 2:

        print(
            "WARNING: Test split contains only "
            "one target class."
        )

    return (
        X_train,
        X_test,
        y_train,
        y_test
    )


# ============================================================
# TRAIN MODEL
# ============================================================

def train_model(
    X_train,
    y_train
):

    print()
    print("=" * 80)
    print("TRAINING RANDOM FOREST MODEL")
    print("=" * 80)

    model = RandomForestClassifier(

        n_estimators=300,

        max_depth=8,

        min_samples_split=10,

        min_samples_leaf=4,

        class_weight="balanced",

        random_state=RANDOM_STATE,

        n_jobs=-1,
    )

    print(
        "Model configuration:"
    )

    print(
        "  Algorithm        : Random Forest"
    )

    print(
        "  Estimators       : 300"
    )

    print(
        "  Max depth        : 8"
    )

    print(
        "  Min samples split: 10"
    )

    print(
        "  Min samples leaf : 4"
    )

    print(
        "  Class weight     : balanced"
    )

    print()

    print(
        "Training model..."
    )

    model.fit(
        X_train,
        y_train
    )

    print(
        "Model training completed."
    )

    return model


# ============================================================
# EVALUATE MODEL
# ============================================================

def evaluate_model(
    model,
    X_test,
    y_test
):

    print()
    print("=" * 80)
    print("MODEL EVALUATION")
    print("=" * 80)

    predictions = model.predict(
        X_test
    )

    probabilities = model.predict_proba(
        X_test
    )

    # Probability of positive class
    if probabilities.shape[1] >= 2:

        positive_probability = (
            probabilities[:, 1]
        )

    else:

        positive_probability = (
            probabilities[:, 0]
        )

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    # --------------------------------------------------------
    # ROC AUC
    # --------------------------------------------------------

    roc_auc = None

    if y_test.nunique() >= 2:

        try:

            roc_auc = roc_auc_score(
                y_test,
                positive_probability
            )

        except Exception:

            roc_auc = None

    # --------------------------------------------------------
    # Print metrics
    # --------------------------------------------------------

    print(
        f"Accuracy  : {accuracy:.4f}"
    )

    print(
        f"Precision : {precision:.4f}"
    )

    print(
        f"Recall    : {recall:.4f}"
    )

    print(
        f"F1 Score  : {f1:.4f}"
    )

    if roc_auc is not None:

        print(
            f"ROC-AUC   : {roc_auc:.4f}"
        )

    else:

        print(
            "ROC-AUC   : N/A"
        )

    # --------------------------------------------------------
    # Classification report
    # --------------------------------------------------------

    print()
    print(
        "Classification Report:"
    )

    print(
        classification_report(
            y_test,
            predictions,
            zero_division=0
        )
    )

    # --------------------------------------------------------
    # Confusion matrix
    # --------------------------------------------------------

    print(
        "Confusion Matrix:"
    )

    print(
        confusion_matrix(
            y_test,
            predictions
        )
    )

    metrics = {

        "accuracy": float(
            accuracy
        ),

        "precision": float(
            precision
        ),

        "recall": float(
            recall
        ),

        "f1_score": float(
            f1
        ),

        "roc_auc": (
            float(roc_auc)
            if roc_auc is not None
            else None
        ),

        "test_rows": int(
            len(y_test)
        ),
    }

    return metrics


# ============================================================
# FEATURE IMPORTANCE
# ============================================================

def show_feature_importance(
    model
):

    print()
    print("=" * 80)
    print("FEATURE IMPORTANCE")
    print("=" * 80)

    importances = pd.DataFrame({

        "feature":
            FEATURE_COLUMNS,

        "importance":
            model.feature_importances_,
    })

    importances = (
        importances
        .sort_values(
            "importance",
            ascending=False
        )
        .reset_index(
            drop=True
        )
    )

    print(
        importances.to_string(
            index=False
        )
    )

    return importances


# ============================================================
# SAVE MODEL
# ============================================================

def save_model(
    model,
    metrics,
    feature_importance
):

    print()
    print("=" * 80)
    print("SAVING MODEL")
    print("=" * 80)

    os.makedirs(
        MODEL_DIR,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Save trained model
    # --------------------------------------------------------

    joblib.dump(
        model,
        MODEL_FILE
    )

    print(
        f"Model saved:"
    )

    print(
        f"  {MODEL_FILE}"
    )

    # --------------------------------------------------------
    # Save feature columns
    # --------------------------------------------------------

    feature_data = {

        "features":
            FEATURE_COLUMNS,

        "feature_count":
            len(FEATURE_COLUMNS),
    }

    with open(
        FEATURE_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            feature_data,
            file,
            indent=4
        )

    print(
        "Feature list saved:"
    )

    print(
        f"  {FEATURE_FILE}"
    )

    # --------------------------------------------------------
    # Add feature importance
    # --------------------------------------------------------

    metrics_to_save = dict(
        metrics
    )

    metrics_to_save[
        "feature_importance"
    ] = {

        row["feature"]:
            float(row["importance"])

        for _, row
        in feature_importance.iterrows()
    }

    metrics_to_save[
        "model_type"
    ] = "RandomForestClassifier"

    metrics_to_save[
        "random_state"
    ] = RANDOM_STATE

    # --------------------------------------------------------
    # Save metrics
    # --------------------------------------------------------

    with open(
        METRICS_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            metrics_to_save,
            file,
            indent=4
        )

    print(
        "Training metrics saved:"
    )

    print(
        f"  {METRICS_FILE}"
    )


# ============================================================
# MAIN TRAINING PIPELINE
# ============================================================

def main():

    print()
    print("=" * 80)
    print("STAGE 20.2 - ML MODEL TRAINING")
    print("=" * 80)

    try:

        # ----------------------------------------------------
        # 1. Load data
        # ----------------------------------------------------

        df = load_training_data()

        # ----------------------------------------------------
        # 2. Validate
        # ----------------------------------------------------

        validate_columns(
            df
        )

        # ----------------------------------------------------
        # 3. Clean
        # ----------------------------------------------------

        df = clean_data(
            df
        )

        # ----------------------------------------------------
        # 4. Prepare X/y
        # ----------------------------------------------------

        X, y = prepare_xy(
            df
        )

        # ----------------------------------------------------
        # 5. Chronological split
        # ----------------------------------------------------

        (
            X_train,
            X_test,
            y_train,
            y_test
        ) = chronological_split(
            X,
            y
        )

        # ----------------------------------------------------
        # 6. Train
        # ----------------------------------------------------

        model = train_model(
            X_train,
            y_train
        )

        # ----------------------------------------------------
        # 7. Evaluate
        # ----------------------------------------------------

        metrics = evaluate_model(
            model,
            X_test,
            y_test
        )

        # ----------------------------------------------------
        # 8. Feature importance
        # ----------------------------------------------------

        feature_importance = (
            show_feature_importance(
                model
            )
        )

        # ----------------------------------------------------
        # 9. Save everything
        # ----------------------------------------------------

        save_model(
            model,
            metrics,
            feature_importance
        )

        # ----------------------------------------------------
        # COMPLETE
        # ----------------------------------------------------

        print()
        print("=" * 80)
        print("STAGE 20.2 MODEL TRAINING COMPLETE")
        print("=" * 80)

        print()
        print(
            "Model:"
        )

        print(
            MODEL_FILE
        )

        print()
        print(
            "Features:"
        )

        print(
            FEATURE_FILE
        )

        print()
        print(
            "Metrics:"
        )

        print(
            METRICS_FILE
        )

        print()
        print(
            "Next step: Stage 20.3 ML prediction."
        )

    except Exception as e:

        print()
        print("=" * 80)
        print("STAGE 20.2 TRAINING FAILED")
        print("=" * 80)

        print(
            f"Error type: {type(e).__name__}"
        )

        print(
            f"Error: {e}"
        )

        raise


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()