"""
============================================================
STAGE 11 - PAPER PORTFOLIO / POSITION TRACKING
============================================================

PURPOSE
-------
Stage 11 takes signals generated by Stage 10 and maintains
a paper-trading portfolio.

PAPER TRADING ONLY
------------------
NO REAL ORDERS ARE PLACED.

LOCKED STRATEGY
---------------
SMMA FAST       = 20
SMMA SLOW       = 120
HOLDING PERIOD  = 60 trading days

RISK MANAGEMENT
---------------
Reference Capital = Rs. 100,000
Risk per Trade    = 1%
Stop Loss         = 5%
Take Profit       = 10%
Maximum Position  = 20%

COST / SLIPPAGE
---------------
Entry Slippage       = 0.10%
Exit Slippage        = 0.10%
Transaction Cost     = 0.05%

INPUT
-----
data/paper_signals.csv

OUTPUT
------
data/paper_trade_history.csv
data/paper_portfolio.csv

IMPORTANT
---------
If Stage 10 produces no new signal, Stage 11 does NOT fail.
It simply maintains the current paper portfolio.
"""


# ============================================================
# IMPORTS
# ============================================================

import os
import pandas as pd

from api.historical_data import get_historical_data


# ============================================================
# STOCKS
# ============================================================

STOCKS = [
    "SBIN-EQ",
    "SUZLON-EQ",
    "IRFC-EQ",
    "TATAMOTORS-EQ",
    "RELIANCE-EQ",
    "ITC-EQ",
]


# ============================================================
# LOCKED PORTFOLIO SETTINGS
# ============================================================

INITIAL_CAPITAL = 100000.0

RISK_PER_TRADE_PERCENT = 1.0

STOP_LOSS_PERCENT = 5.0

TAKE_PROFIT_PERCENT = 10.0

MAX_POSITION_PERCENT = 20.0

HOLDING_PERIOD = 60


# ============================================================
# COST / SLIPPAGE SETTINGS
# ============================================================

ENTRY_SLIPPAGE_PERCENT = 0.10

EXIT_SLIPPAGE_PERCENT = 0.10

TRANSACTION_COST_PERCENT = 0.05


# ============================================================
# FILE SETTINGS
# ============================================================

DATA_DIRECTORY = "data"

SIGNALS_FILE = os.path.join(
    DATA_DIRECTORY,
    "paper_signals.csv"
)

TRADE_HISTORY_FILE = os.path.join(
    DATA_DIRECTORY,
    "paper_trade_history.csv"
)

PORTFOLIO_FILE = os.path.join(
    DATA_DIRECTORY,
    "paper_portfolio.csv"
)


# ============================================================
# CREATE DATA DIRECTORY
# ============================================================

os.makedirs(
    DATA_DIRECTORY,
    exist_ok=True
)


# ============================================================
# SAFE FLOAT
# ============================================================

def safe_float(value, default=0.0):

    try:

        if pd.isna(value):
            return default

        return float(value)

    except Exception:

        return default


# ============================================================
# LOAD PAPER SIGNALS
# ============================================================

def load_paper_signals():

    if not os.path.exists(SIGNALS_FILE):

        print()
        print(
            "⚠️ No paper signal file found."
        )

        print(
            f"   Expected: {SIGNALS_FILE}"
        )

        print(
            "   Stage 10 may simply have generated "
            "no new crossover."
        )

        return pd.DataFrame()

    try:

        df = pd.read_csv(
            SIGNALS_FILE
        )

    except Exception as error:

        print(
            f"⚠️ Could not read paper signals: "
            f"{error}"
        )

        return pd.DataFrame()

    if df.empty:

        print(
            "⚠️ paper_signals.csv is empty."
        )

        return pd.DataFrame()

    required_columns = [
        "Symbol",
        "Signal Date",
        "Signal",
        "Entry Price",
        "Stop Loss",
        "Take Profit",
        "Shares",
    ]

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:

        print(
            "❌ Missing columns in "
            "paper_signals.csv:"
        )

        for column in missing:

            print(
                f"   - {column}"
            )

        return pd.DataFrame()

    # --------------------------------------------------------
    # Normalize date
    # --------------------------------------------------------

    df["Signal Date"] = pd.to_datetime(
        df["Signal Date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Normalize numeric columns
    # --------------------------------------------------------

    numeric_columns = [
        "Entry Price",
        "Stop Loss",
        "Take Profit",
        "Shares",
    ]

    for column in numeric_columns:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Remove invalid records
    # --------------------------------------------------------

    df = df.dropna(
        subset=[
            "Symbol",
            "Signal Date",
            "Signal",
            "Entry Price",
            "Stop Loss",
            "Take Profit",
            "Shares",
        ]
    )

    # --------------------------------------------------------
    # Normalize signal
    # --------------------------------------------------------

    df["Signal"] = (
        df["Signal"]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    # --------------------------------------------------------
    # Keep only BUY / SELL
    # --------------------------------------------------------

    df = df[
        df["Signal"].isin(
            ["BUY", "SELL"]
        )
    ]

    # --------------------------------------------------------
    # Sort
    # --------------------------------------------------------

    df = (
        df
        .sort_values("Signal Date")
        .reset_index(drop=True)
    )

    return df


# ============================================================
# LOAD TRADE HISTORY
# ============================================================

def load_trade_history():

    if not os.path.exists(
        TRADE_HISTORY_FILE
    ):

        return pd.DataFrame()

    try:

        df = pd.read_csv(
            TRADE_HISTORY_FILE
        )

        if df.empty:

            return pd.DataFrame()

        # ----------------------------------------------------
        # Convert dates
        # ----------------------------------------------------

        date_columns = [
            "Signal Date",
            "Entry Date",
            "Exit Date",
        ]

        for column in date_columns:

            if column in df.columns:

                df[column] = pd.to_datetime(
                    df[column],
                    errors="coerce"
                )

        # ----------------------------------------------------
        # Normalize numeric columns
        # ----------------------------------------------------

        numeric_columns = [
            "Entry Price",
            "Stop Loss",
            "Take Profit",
            "Shares",
            "Exit Price",
            "Latest Price",
            "Gross PnL",
            "Transaction Costs",
            "Net PnL",
            "Return %",
            "Bars Held",
        ]

        for column in numeric_columns:

            if column in df.columns:

                df[column] = pd.to_numeric(
                    df[column],
                    errors="coerce"
                )

        return df

    except Exception as error:

        print(
            f"⚠️ Could not read trade history: "
            f"{error}"
        )

        return pd.DataFrame()


# ============================================================
# SAVE TRADE HISTORY
# ============================================================

def save_trade_history(
    df
):

    if df is None or df.empty:

        return

    output = df.copy()

    # --------------------------------------------------------
    # Format dates
    # --------------------------------------------------------

    date_columns = [
        "Signal Date",
        "Entry Date",
        "Exit Date",
    ]

    for column in date_columns:

        if column in output.columns:

            dates = pd.to_datetime(
                output[column],
                errors="coerce"
            )

            output[column] = dates.dt.strftime(
                "%Y-%m-%d"
            )

    output.to_csv(
        TRADE_HISTORY_FILE,
        index=False
    )


# ============================================================
# BUILD SIGNAL ID
# ============================================================

def build_signal_id(
    symbol,
    signal_date,
    signal
):

    date_text = pd.Timestamp(
        signal_date
    ).strftime("%Y-%m-%d")

    return (
        f"{symbol}|"
        f"{date_text}|"
        f"{signal}"
    )


# ============================================================
# CHECK DUPLICATE SIGNAL
# ============================================================

def signal_already_processed(
    signal_id,
    history
):

    if history.empty:

        return False

    if "Signal ID" not in history.columns:

        return False

    return (
        history["Signal ID"]
        .astype(str)
        .eq(signal_id)
        .any()
    )


# ============================================================
# GET CURRENT MARKET DATA
# ============================================================

def get_current_data(
    symbol
):

    try:

        df = get_historical_data(
            symbol,
            days=250
        )

    except Exception as error:

        print(
            f"❌ Data error for "
            f"{symbol}: {error}"
        )

        return None

    if df is None or df.empty:

        return None

    df = df.copy()

    # --------------------------------------------------------
    # Normalize column names
    # --------------------------------------------------------

    df.columns = [
        str(column)
        .strip()
        .lower()
        for column in df.columns
    ]

    required = [
        "date",
        "open",
        "high",
        "low",
        "close",
    ]

    for column in required:

        if column not in df.columns:

            print(
                f"❌ {symbol}: missing "
                f"{column} column"
            )

            return None

    # --------------------------------------------------------
    # Convert date
    # --------------------------------------------------------

    df["date"] = pd.to_datetime(
        df["date"],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Convert prices
    # --------------------------------------------------------

    for column in [
        "open",
        "high",
        "low",
        "close",
    ]:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Remove invalid rows
    # --------------------------------------------------------

    df = df.dropna(
        subset=[
            "date",
            "open",
            "high",
            "low",
            "close",
        ]
    )

    # --------------------------------------------------------
    # Sort
    # --------------------------------------------------------

    df = (
        df
        .sort_values("date")
        .reset_index(drop=True)
    )

    return df


# ============================================================
# ENTRY TRANSACTION COST
# ============================================================

def calculate_entry_cost(
    entry_price,
    shares
):

    entry_value = (
        entry_price
        *
        shares
    )

    transaction_cost = (
        entry_value
        *
        TRANSACTION_COST_PERCENT
        /
        100.0
    )

    return transaction_cost


# ============================================================
# EXIT TRANSACTION COST
# ============================================================

def calculate_exit_cost(
    exit_price,
    shares
):

    exit_value = (
        exit_price
        *
        shares
    )

    transaction_cost = (
        exit_value
        *
        TRANSACTION_COST_PERCENT
        /
        100.0
    )

    return transaction_cost


# ============================================================
# APPLY EXIT SLIPPAGE
# ============================================================

def apply_exit_slippage(
    price,
    signal
):

    if signal == "BUY":

        # Closing a long position means selling.
        # Exit price is slightly worse.

        return (
            price
            *
            (
                1
                -
                EXIT_SLIPPAGE_PERCENT
                /
                100.0
            )
        )

    if signal == "SELL":

        # Closing a short position means buying back.
        # Exit price is slightly worse.

        return (
            price
            *
            (
                1
                +
                EXIT_SLIPPAGE_PERCENT
                /
                100.0
            )
        )

    return price


# ============================================================
# CALCULATE GROSS PNL
# ============================================================

def calculate_gross_pnl(
    signal,
    entry_price,
    exit_price,
    shares
):

    if signal == "BUY":

        return (
            exit_price
            -
            entry_price
        ) * shares

    if signal == "SELL":

        return (
            entry_price
            -
            exit_price
        ) * shares

    return 0.0


# ============================================================
# SIMULATE ONE PAPER POSITION
# ============================================================

def simulate_position(
    signal_row,
    market_data
):

    signal = str(
        signal_row["Signal"]
    ).upper()

    signal_date = pd.Timestamp(
        signal_row["Signal Date"]
    ).normalize()

    entry_price = safe_float(
        signal_row["Entry Price"]
    )

    stop_loss = safe_float(
        signal_row["Stop Loss"]
    )

    take_profit = safe_float(
        signal_row["Take Profit"]
    )

    shares = int(
        safe_float(
            signal_row["Shares"]
        )
    )

    # --------------------------------------------------------
    # Validate
    # --------------------------------------------------------

    if shares <= 0:

        return {
            "status": "INVALID",
            "reason": "INVALID_SHARES",
        }

    if entry_price <= 0:

        return {
            "status": "INVALID",
            "reason": "INVALID_ENTRY_PRICE",
        }

    # --------------------------------------------------------
    # Find signal candle
    # --------------------------------------------------------

    dates = pd.to_datetime(
        market_data["date"]
    ).dt.normalize()

    signal_indexes = market_data.index[
        dates == signal_date
    ]

    # --------------------------------------------------------
    # If exact date isn't found, find first date after it.
    # --------------------------------------------------------

    if len(signal_indexes) == 0:

        signal_indexes = market_data.index[
            dates > signal_date
        ]

    if len(signal_indexes) == 0:

        return {
            "status": "INVALID",
            "reason": "SIGNAL_DATE_NOT_FOUND",
        }

    signal_index = signal_indexes[0]

    # --------------------------------------------------------
    # Only candles after signal candle are used.
    # --------------------------------------------------------

    future_data = market_data.loc[
        signal_index + 1:
    ].copy()

    # --------------------------------------------------------
    # No future candle yet.
    # --------------------------------------------------------

    if future_data.empty:

        latest = market_data.iloc[-1]

        return {
            "status": "OPEN",
            "reason": "WAITING_FOR_NEXT_CANDLE",
            "exit_date": None,
            "exit_price": None,
            "shares": shares,
            "latest_price": safe_float(
                latest["close"]
            ),
            "bars_held": 0,
        }

    # --------------------------------------------------------
    # Maximum holding period
    # --------------------------------------------------------

    check_data = future_data.head(
        HOLDING_PERIOD
    )

    bars_held = 0

    # ========================================================
    # PROCESS EACH FUTURE CANDLE
    # ========================================================

    for _, candle in check_data.iterrows():

        bars_held += 1

        high = safe_float(
            candle["high"]
        )

        low = safe_float(
            candle["low"]
        )

        close = safe_float(
            candle["close"]
        )

        candle_date = pd.Timestamp(
            candle["date"]
        ).normalize()

        # ====================================================
        # LONG POSITION
        # ====================================================

        if signal == "BUY":

            hit_stop = (
                low <= stop_loss
            )

            hit_target = (
                high >= take_profit
            )

            # Conservative assumption:
            # if both happen on same candle,
            # stop loss is triggered first.

            if hit_stop:

                raw_exit = stop_loss

                exit_price = apply_exit_slippage(
                    raw_exit,
                    signal
                )

                return {
                    "status": "CLOSED",
                    "reason": "STOP_LOSS",
                    "exit_date": candle_date,
                    "exit_price": exit_price,
                    "shares": shares,
                    "latest_price": close,
                    "bars_held": bars_held,
                }

            if hit_target:

                raw_exit = take_profit

                exit_price = apply_exit_slippage(
                    raw_exit,
                    signal
                )

                return {
                    "status": "CLOSED",
                    "reason": "TAKE_PROFIT",
                    "exit_date": candle_date,
                    "exit_price": exit_price,
                    "shares": shares,
                    "latest_price": close,
                    "bars_held": bars_held,
                }

        # ====================================================
        # SHORT POSITION
        # ====================================================

        elif signal == "SELL":

            hit_stop = (
                high >= stop_loss
            )

            hit_target = (
                low <= take_profit
            )

            # Conservative assumption:
            # stop loss first if both are hit.

            if hit_stop:

                raw_exit = stop_loss

                exit_price = apply_exit_slippage(
                    raw_exit,
                    signal
                )

                return {
                    "status": "CLOSED",
                    "reason": "STOP_LOSS",
                    "exit_date": candle_date,
                    "exit_price": exit_price,
                    "shares": shares,
                    "latest_price": close,
                    "bars_held": bars_held,
                }

            if hit_target:

                raw_exit = take_profit

                exit_price = apply_exit_slippage(
                    raw_exit,
                    signal
                )

                return {
                    "status": "CLOSED",
                    "reason": "TAKE_PROFIT",
                    "exit_date": candle_date,
                    "exit_price": exit_price,
                    "shares": shares,
                    "latest_price": close,
                    "bars_held": bars_held,
                }

    # ========================================================
    # TIME EXIT
    # ========================================================

    if len(check_data) >= HOLDING_PERIOD:

        last_candle = check_data.iloc[
            HOLDING_PERIOD - 1
        ]

        raw_exit = safe_float(
            last_candle["close"]
        )

        exit_price = apply_exit_slippage(
            raw_exit,
            signal
        )

        return {
            "status": "CLOSED",
            "reason": "TIME_EXIT",
            "exit_date": pd.Timestamp(
                last_candle["date"]
            ).normalize(),
            "exit_price": exit_price,
            "shares": shares,
            "latest_price": raw_exit,
            "bars_held": HOLDING_PERIOD,
        }

    # ========================================================
    # STILL OPEN
    # ========================================================

    latest = market_data.iloc[-1]

    latest_price = safe_float(
        latest["close"]
    )

    return {
        "status": "OPEN",
        "reason": "POSITION_OPEN",
        "exit_date": None,
        "exit_price": None,
        "shares": shares,
        "latest_price": latest_price,
        "bars_held": bars_held,
    }


# ============================================================
# BUILD TRADE RECORD
# ============================================================

def build_trade_record(
    signal_row,
    result
):

    symbol = str(
        signal_row["Symbol"]
    )

    stock = str(
        signal_row.get(
            "Stock",
            symbol.replace(
                "-EQ",
                ""
            )
        )
    )

    signal = str(
        signal_row["Signal"]
    ).upper()

    signal_date = pd.Timestamp(
        signal_row["Signal Date"]
    ).normalize()

    entry_price = safe_float(
        signal_row["Entry Price"]
    )

    stop_loss = safe_float(
        signal_row["Stop Loss"]
    )

    take_profit = safe_float(
        signal_row["Take Profit"]
    )

    shares = int(
        safe_float(
            signal_row["Shares"]
        )
    )

    status = result.get(
        "status",
        "UNKNOWN"
    )

    reason = result.get(
        "reason",
        ""
    )

    exit_price = result.get(
        "exit_price"
    )

    latest_price = safe_float(
        result.get(
            "latest_price",
            entry_price
        )
    )

    bars_held = int(
        result.get(
            "bars_held",
            0
        )
    )

    # ========================================================
    # OPEN POSITION
    # ========================================================

    if status == "OPEN":

        if signal == "BUY":

            unrealized_pnl = (
                latest_price
                -
                entry_price
            ) * shares

        else:

            unrealized_pnl = (
                entry_price
                -
                latest_price
            ) * shares

        entry_cost = calculate_entry_cost(
            entry_price,
            shares
        )

        net_pnl = (
            unrealized_pnl
            -
            entry_cost
        )

        position_value = (
            entry_price
            *
            shares
        )

        return_percent = 0.0

        if position_value > 0:

            return_percent = (
                net_pnl
                /
                position_value
                *
                100
            )

        return {

            "Signal ID":
                build_signal_id(
                    symbol,
                    signal_date,
                    signal
                ),

            "Stock":
                stock,

            "Symbol":
                symbol,

            "Signal Date":
                signal_date,

            "Signal":
                signal,

            "Entry Date":
                signal_date,

            "Entry Price":
                entry_price,

            "Stop Loss":
                stop_loss,

            "Take Profit":
                take_profit,

            "Shares":
                shares,

            "Exit Date":
                None,

            "Exit Price":
                None,

            "Bars Held":
                bars_held,

            "Exit Reason":
                reason,

            "Status":
                "OPEN",

            "Latest Price":
                latest_price,

            "Gross PnL":
                unrealized_pnl,

            "Transaction Costs":
                entry_cost,

            "Net PnL":
                net_pnl,

            "Return %":
                return_percent,
        }

    # ========================================================
    # CLOSED POSITION
    # ========================================================

    if status == "CLOSED":

        exit_price = safe_float(
            exit_price
        )

        gross_pnl = calculate_gross_pnl(
            signal,
            entry_price,
            exit_price,
            shares
        )

        entry_cost = calculate_entry_cost(
            entry_price,
            shares
        )

        exit_cost = calculate_exit_cost(
            exit_price,
            shares
        )

        total_cost = (
            entry_cost
            +
            exit_cost
        )

        net_pnl = (
            gross_pnl
            -
            total_cost
        )

        position_value = (
            entry_price
            *
            shares
        )

        return_percent = 0.0

        if position_value > 0:

            return_percent = (
                net_pnl
                /
                position_value
                *
                100
            )

        return {

            "Signal ID":
                build_signal_id(
                    symbol,
                    signal_date,
                    signal
                ),

            "Stock":
                stock,

            "Symbol":
                symbol,

            "Signal Date":
                signal_date,

            "Signal":
                signal,

            "Entry Date":
                signal_date,

            "Entry Price":
                entry_price,

            "Stop Loss":
                stop_loss,

            "Take Profit":
                take_profit,

            "Shares":
                shares,

            "Exit Date":
                result.get(
                    "exit_date"
                ),

            "Exit Price":
                exit_price,

            "Bars Held":
                bars_held,

            "Exit Reason":
                reason,

            "Status":
                "CLOSED",

            "Latest Price":
                latest_price,

            "Gross PnL":
                gross_pnl,

            "Transaction Costs":
                total_cost,

            "Net PnL":
                net_pnl,

            "Return %":
                return_percent,
        }

    return None


# ============================================================
# PROCESS ONE SIGNAL
# ============================================================

def process_signal(
    signal_row,
    history
):

    symbol = str(
        signal_row["Symbol"]
    )

    signal = str(
        signal_row["Signal"]
    ).upper()

    signal_date = pd.Timestamp(
        signal_row["Signal Date"]
    ).normalize()

    signal_id = build_signal_id(
        symbol,
        signal_date,
        signal
    )

    # --------------------------------------------------------
    # Duplicate protection
    # --------------------------------------------------------

    if signal_already_processed(
        signal_id,
        history
    ):

        print(
            f"⏭️ Already processed: "
            f"{symbol} "
            f"{signal} "
            f"{signal_date.strftime('%Y-%m-%d')}"
        )

        return None

    print()
    print(
        "-" * 90
    )

    print(
        f"Processing {symbol} "
        f"{signal} signal..."
    )

    print(
        f"Signal date : "
        f"{signal_date.strftime('%Y-%m-%d')}"
    )

    print(
        f"Entry       : "
        f"Rs. {safe_float(signal_row['Entry Price']):.2f}"
    )

    print(
        f"Stop Loss   : "
        f"Rs. {safe_float(signal_row['Stop Loss']):.2f}"
    )

    print(
        f"Take Profit : "
        f"Rs. {safe_float(signal_row['Take Profit']):.2f}"
    )

    print(
        f"Shares      : "
        f"{int(safe_float(signal_row['Shares']))}"
    )

    # --------------------------------------------------------
    # Current market data
    # --------------------------------------------------------

    market_data = get_current_data(
        symbol
    )

    if market_data is None:

        print(
            f"❌ Could not get data "
            f"for {symbol}"
        )

        return None

    print(
        f"Historical rows: "
        f"{len(market_data)}"
    )

    # --------------------------------------------------------
    # Simulate
    # --------------------------------------------------------

    result = simulate_position(
        signal_row,
        market_data
    )

    if result is None:

        return None

    if result.get("status") == "INVALID":

        print(
            f"❌ Invalid position: "
            f"{result.get('reason')}"
        )

        return None

    trade = build_trade_record(
        signal_row,
        result
    )

    if trade is None:

        return None

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------

    print()
    print(
        f"Status       : "
        f"{trade['Status']}"
    )

    print(
        f"Exit reason  : "
        f"{trade['Exit Reason']}"
    )

    print(
        f"Bars held    : "
        f"{trade['Bars Held']}"
    )

    print(
        f"Latest price : "
        f"Rs. {trade['Latest Price']:.2f}"
    )

    if trade["Status"] == "CLOSED":

        exit_date = trade["Exit Date"]

        if exit_date is not None:

            print(
                f"Exit date    : "
                f"{pd.Timestamp(exit_date).strftime('%Y-%m-%d')}"
            )

        print(
            f"Exit price   : "
            f"Rs. {trade['Exit Price']:.2f}"
        )

    print(
        f"Net PnL      : "
        f"Rs. {trade['Net PnL']:.2f}"
    )

    print(
        f"Return       : "
        f"{trade['Return %']:.2f}%"
    )

    return trade


# ============================================================
# REFRESH OPEN POSITIONS
# ============================================================

def refresh_open_positions(
    history
):

    if history.empty:

        return history

    if "Status" not in history.columns:

        return history

    open_indexes = history.index[
        history["Status"]
        .astype(str)
        .str.upper()
        .eq("OPEN")
    ]

    if len(open_indexes) == 0:

        return history

    print()
    print(
        "=" * 100
    )

    print(
        "REFRESHING OPEN POSITIONS"
    )

    print(
        "=" * 100
    )

    for index in open_indexes:

        row = history.loc[
            index
        ]

        symbol = str(
            row["Symbol"]
        )

        signal = str(
            row["Signal"]
        ).upper()

        print()
        print(
            f"Checking open position: "
            f"{symbol} {signal}"
        )

        market_data = get_current_data(
            symbol
        )

        if market_data is None:

            print(
                "⚠️ Could not refresh "
                "this position."
            )

            continue

        signal_row = pd.Series({

            "Symbol":
                symbol,

            "Stock":
                row.get(
                    "Stock",
                    symbol.replace(
                        "-EQ",
                        ""
                    )
                ),

            "Signal Date":
                row["Signal Date"],

            "Signal":
                signal,

            "Entry Price":
                row["Entry Price"],

            "Stop Loss":
                row["Stop Loss"],

            "Take Profit":
                row["Take Profit"],

            "Shares":
                row["Shares"],
        })

        result = simulate_position(
            signal_row,
            market_data
        )

        trade = build_trade_record(
            signal_row,
            result
        )

        if trade is None:

            continue

        for column in trade:

            if column in history.columns:

                history.at[
                    index,
                    column
                ] = trade[column]

        print(
            f"Status: "
            f"{trade['Status']}"
        )

        print(
            f"Net PnL: "
            f"Rs. {trade['Net PnL']:.2f}"
        )

    return history


# ============================================================
# CREATE PORTFOLIO SUMMARY
# ============================================================

def create_portfolio_summary(
    history
):

    if history.empty:

        return {

            "starting_capital":
                INITIAL_CAPITAL,

            "realized_pnl":
                0.0,

            "unrealized_pnl":
                0.0,

            "net_pnl":
                0.0,

            "portfolio_value":
                INITIAL_CAPITAL,

            "open_positions":
                0,

            "closed_trades":
                0,

            "wins":
                0,

            "losses":
                0,
        }

    status_series = (
        history["Status"]
        .astype(str)
        .str.upper()
    )

    closed = history[
        status_series == "CLOSED"
    ].copy()

    open_positions = history[
        status_series == "OPEN"
    ].copy()

    # --------------------------------------------------------
    # Realized PnL
    # --------------------------------------------------------

    realized_pnl = 0.0

    if not closed.empty:

        realized_pnl = (
            pd.to_numeric(
                closed["Net PnL"],
                errors="coerce"
            )
            .fillna(0)
            .sum()
        )

    # --------------------------------------------------------
    # Unrealized PnL
    # --------------------------------------------------------

    unrealized_pnl = 0.0

    if not open_positions.empty:

        unrealized_pnl = (
            pd.to_numeric(
                open_positions["Net PnL"],
                errors="coerce"
            )
            .fillna(0)
            .sum()
        )

    # --------------------------------------------------------
    # Total PnL
    # --------------------------------------------------------

    net_pnl = (
        realized_pnl
        +
        unrealized_pnl
    )

    # --------------------------------------------------------
    # Wins / losses
    # --------------------------------------------------------

    wins = 0
    losses = 0

    if not closed.empty:

        net_values = pd.to_numeric(
            closed["Net PnL"],
            errors="coerce"
        ).fillna(0)

        wins = int(
            (net_values > 0).sum()
        )

        losses = int(
            (net_values < 0).sum()
        )

    # --------------------------------------------------------
    # Portfolio value
    # --------------------------------------------------------

    portfolio_value = (
        INITIAL_CAPITAL
        +
        net_pnl
    )

    return {

        "starting_capital":
            INITIAL_CAPITAL,

        "realized_pnl":
            float(realized_pnl),

        "unrealized_pnl":
            float(unrealized_pnl),

        "net_pnl":
            float(net_pnl),

        "portfolio_value":
            float(portfolio_value),

        "open_positions":
            len(open_positions),

        "closed_trades":
            len(closed),

        "wins":
            wins,

        "losses":
            losses,
    }


# ============================================================
# SAVE PORTFOLIO
# ============================================================

def save_portfolio(
    history,
    summary
):

    rows = []

    # --------------------------------------------------------
    # Open positions
    # --------------------------------------------------------

    if not history.empty:

        status_series = (
            history["Status"]
            .astype(str)
            .str.upper()
        )

        open_positions = history[
            status_series == "OPEN"
        ]

        for _, row in open_positions.iterrows():

            rows.append({

                "Stock":
                    row["Stock"],

                "Symbol":
                    row["Symbol"],

                "Signal":
                    row["Signal"],

                "Signal Date":
                    row["Signal Date"],

                "Entry Price":
                    row["Entry Price"],

                "Shares":
                    row["Shares"],

                "Stop Loss":
                    row["Stop Loss"],

                "Take Profit":
                    row["Take Profit"],

                "Latest Price":
                    row["Latest Price"],

                "Bars Held":
                    row["Bars Held"],

                "Unrealized Net PnL":
                    row["Net PnL"],

                "Return %":
                    row["Return %"],

                "Status":
                    "OPEN",
            })

    # --------------------------------------------------------
    # No open positions
    # --------------------------------------------------------

    if not rows:

        portfolio_df = pd.DataFrame([{

            "Stock":
                "-",

            "Symbol":
                "-",

            "Signal":
                "-",

            "Signal Date":
                "",

            "Entry Price":
                0.0,

            "Shares":
                0,

            "Stop Loss":
                0.0,

            "Take Profit":
                0.0,

            "Latest Price":
                0.0,

            "Bars Held":
                0,

            "Unrealized Net PnL":
                0.0,

            "Return %":
                0.0,

            "Status":
                "NO_OPEN_POSITIONS",
        }])

    else:

        portfolio_df = pd.DataFrame(
            rows
        )

    portfolio_df.to_csv(
        PORTFOLIO_FILE,
        index=False
    )


# ============================================================
# PRINT TRADE HISTORY
# ============================================================

def print_trade_history(
    history
):

    if history.empty:

        print()
        print(
            "No paper trades recorded."
        )

        return

    print()
    print(
        "=" * 110
    )

    print(
        "PAPER TRADE HISTORY"
    )

    print(
        "=" * 110
    )

    columns = [
        "Stock",
        "Signal",
        "Signal Date",
        "Entry Price",
        "Shares",
        "Exit Price",
        "Exit Reason",
        "Status",
        "Net PnL",
        "Return %",
    ]

    available = [
        column
        for column in columns
        if column in history.columns
    ]

    display_df = history[
        available
    ].copy()

    print(
        display_df.to_string(
            index=False
        )
    )


# ============================================================
# PRINT OPEN POSITIONS
# ============================================================

def print_open_positions(
    history
):

    print()
    print(
        "=" * 100
    )

    print(
        "OPEN PAPER POSITIONS"
    )

    print(
        "=" * 100
    )

    if history.empty:

        print(
            "No open positions."
        )

        return

    status_series = (
        history["Status"]
        .astype(str)
        .str.upper()
    )

    open_positions = history[
        status_series == "OPEN"
    ]

    if open_positions.empty:

        print(
            "No open positions."
        )

        return

    columns = [
        "Stock",
        "Signal",
        "Entry Price",
        "Shares",
        "Stop Loss",
        "Take Profit",
        "Latest Price",
        "Bars Held",
        "Net PnL",
        "Return %",
    ]

    available = [
        column
        for column in columns
        if column in open_positions.columns
    ]

    print(
        open_positions[
            available
        ].to_string(
            index=False
        )
    )


# ============================================================
# PRINT SUMMARY
# ============================================================

def print_summary(
    summary
):

    print()
    print(
        "=" * 100
    )

    print(
        "STAGE 11 - PORTFOLIO SUMMARY"
    )

    print(
        "=" * 100
    )

    print(
        f"Starting Capital       : "
        f"Rs. {summary['starting_capital']:,.2f}"
    )

    print(
        f"Realized PnL           : "
        f"Rs. {summary['realized_pnl']:,.2f}"
    )

    print(
        f"Unrealized PnL         : "
        f"Rs. {summary['unrealized_pnl']:,.2f}"
    )

    print(
        f"Total Net PnL          : "
        f"Rs. {summary['net_pnl']:,.2f}"
    )

    print(
        f"Portfolio Value        : "
        f"Rs. {summary['portfolio_value']:,.2f}"
    )

    # --------------------------------------------------------
    # Portfolio return
    # --------------------------------------------------------

    total_return = 0.0

    if summary["starting_capital"] > 0:

        total_return = (
            summary["net_pnl"]
            /
            summary["starting_capital"]
            *
            100
        )

    print(
        f"Portfolio Return       : "
        f"{total_return:.2f}%"
    )

    print(
        f"Open Positions         : "
        f"{summary['open_positions']}"
    )

    print(
        f"Closed Trades          : "
        f"{summary['closed_trades']}"
    )

    print(
        f"Wins                   : "
        f"{summary['wins']}"
    )

    print(
        f"Losses                 : "
        f"{summary['losses']}"
    )

    # --------------------------------------------------------
    # Win rate
    # --------------------------------------------------------

    total_decided = (
        summary["wins"]
        +
        summary["losses"]
    )

    if total_decided > 0:

        win_rate = (
            summary["wins"]
            /
            total_decided
            *
            100
        )

    else:

        win_rate = 0.0

    print(
        f"Win Rate               : "
        f"{win_rate:.2f}%"
    )

    print(
        "=" * 100
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print(
        "=" * 100
    )

    print(
        "          STAGE 11 - PAPER PORTFOLIO"
    )

    print(
        "=" * 100
    )

    print()
    print(
        "⚠️ PAPER TRADING ONLY"
    )

    print(
        "⚠️ NO REAL ORDERS WILL BE PLACED"
    )

    print()

    # ========================================================
    # LOCKED STRATEGY
    # ========================================================

    print(
        "LOCKED STRATEGY"
    )

    print(
        "SMMA                 : 20/120"
    )

    print(
        f"Holding Period       : "
        f"{HOLDING_PERIOD} trading days"
    )

    print(
        f"Initial Capital      : "
        f"Rs. {INITIAL_CAPITAL:,.2f}"
    )

    print(
        f"Risk Per Trade       : "
        f"{RISK_PER_TRADE_PERCENT:.2f}%"
    )

    print(
        f"Stop Loss            : "
        f"{STOP_LOSS_PERCENT:.2f}%"
    )

    print(
        f"Take Profit          : "
        f"{TAKE_PROFIT_PERCENT:.2f}%"
    )

    print(
        f"Maximum Position     : "
        f"{MAX_POSITION_PERCENT:.2f}%"
    )

    print(
        f"Entry Slippage       : "
        f"{ENTRY_SLIPPAGE_PERCENT:.2f}%"
    )

    print(
        f"Exit Slippage        : "
        f"{EXIT_SLIPPAGE_PERCENT:.2f}%"
    )

    print(
        f"Transaction Cost     : "
        f"{TRANSACTION_COST_PERCENT:.2f}%"
    )

    print()

    print(
        "=" * 100
    )

    # ========================================================
    # LOAD EXISTING HISTORY FIRST
    # ========================================================

    history = load_trade_history()

    print(
        f"Existing trade records: "
        f"{len(history)}"
    )

    # ========================================================
    # REFRESH EXISTING OPEN POSITIONS
    # ========================================================

    history = refresh_open_positions(
        history
    )

    # ========================================================
    # LOAD STAGE 10 SIGNALS
    # ========================================================

    signals = load_paper_signals()

    # ========================================================
    # IMPORTANT:
    # NO SIGNALS IS A NORMAL STATE
    # ========================================================

    if signals.empty:

        print()
        print(
            "=" * 100
        )

        print(
            "NO CURRENT PAPER SIGNALS"
        )

        print(
            "=" * 100
        )

        print()
        print(
            "Stage 10 did not provide any new "
            "paper-trading signals."
        )

        print(
            "This is a normal state and NOT an error."
        )

        # ----------------------------------------------------
        # Save existing history
        # ----------------------------------------------------

        save_trade_history(
            history
        )

        # ----------------------------------------------------
        # Create current portfolio
        # ----------------------------------------------------

        summary = create_portfolio_summary(
            history
        )

        save_portfolio(
            history,
            summary
        )

        # ----------------------------------------------------
        # Print current state
        # ----------------------------------------------------

        print_trade_history(
            history
        )

        print_open_positions(
            history
        )

        print_summary(
            summary
        )

        # ----------------------------------------------------
        # Output files
        # ----------------------------------------------------

        print()
        print(
            "=" * 100
        )

        print(
            "OUTPUT FILES"
        )

        print(
            "=" * 100
        )

        print(
            f"Trade History : "
            f"{TRADE_HISTORY_FILE}"
        )

        print(
            f"Portfolio     : "
            f"{PORTFOLIO_FILE}"
        )

        print(
            "=" * 100
        )

        # ----------------------------------------------------
        # Final status
        # ----------------------------------------------------

        print()
        print(
            "=" * 100
        )

        print(
            "RESULT: NO NEW PAPER SIGNALS"
        )

        print()

        print(
            "No new SMMA 20/120 crossover "
            "was detected."
        )

        print(
            "Existing paper positions, if any, "
            "have been refreshed."
        )

        print()
        print(
            "No real order has been placed."
        )

        print(
            "=" * 100
        )

        print()
        print(
            "STAGE 11 COMPLETE"
        )

        print(
            "=" * 100
        )

        return

    # ========================================================
    # SIGNALS AVAILABLE
    # ========================================================

    print()
    print(
        f"Paper signals loaded: "
        f"{len(signals)}"
    )

    # ========================================================
    # PROCESS NEW SIGNALS
    # ========================================================

    new_trades = []

    for _, signal_row in signals.iterrows():

        trade = process_signal(
            signal_row,
            history
        )

        if trade is not None:

            new_trades.append(
                trade
            )

    # ========================================================
    # ADD NEW TRADES
    # ========================================================

    if new_trades:

        new_df = pd.DataFrame(
            new_trades
        )

        if history.empty:

            history = new_df

        else:

            history = pd.concat(
                [
                    history,
                    new_df,
                ],
                ignore_index=True
            )

    # ========================================================
    # REMOVE DUPLICATES
    # ========================================================

    if (
        not history.empty
        and
        "Signal ID" in history.columns
    ):

        history = (
            history
            .drop_duplicates(
                subset=[
                    "Signal ID"
                ],
                keep="last"
            )
            .reset_index(drop=True)
        )

    # ========================================================
    # SAVE TRADE HISTORY
    # ========================================================

    save_trade_history(
        history
    )

    # ========================================================
    # CREATE SUMMARY
    # ========================================================

    summary = create_portfolio_summary(
        history
    )

    # ========================================================
    # SAVE PORTFOLIO
    # ========================================================

    save_portfolio(
        history,
        summary
    )

    # ========================================================
    # PRINT DETAILS
    # ========================================================

    print_trade_history(
        history
    )

    print_open_positions(
        history
    )

    print_summary(
        summary
    )

    # ========================================================
    # OUTPUT FILES
    # ========================================================

    print()
    print(
        "=" * 100
    )

    print(
        "OUTPUT FILES"
    )

    print(
        "=" * 100
    )

    print(
        f"Trade History : "
        f"{TRADE_HISTORY_FILE}"
    )

    print(
        f"Portfolio     : "
        f"{PORTFOLIO_FILE}"
    )

    print(
        "=" * 100
    )

    # ========================================================
    # FINAL VALIDATION
    # ========================================================

    print()
    print(
        "=" * 100
    )

    if summary["net_pnl"] > 0:

        print(
            "RESULT: POSITIVE PAPER PORTFOLIO"
        )

        print()

        print(
            "The paper portfolio is currently "
            "profitable under the locked assumptions."
        )

    elif summary["net_pnl"] < 0:

        print(
            "RESULT: NEGATIVE PAPER PORTFOLIO"
        )

        print()

        print(
            "The paper portfolio is currently "
            "below the starting capital."
        )

    else:

        print(
            "RESULT: BREAK-EVEN / NO CLOSED PNL"
        )

        print()

        print(
            "There is currently no net portfolio "
            "profit or loss."
        )

    print()

    print(
        "No real order has been placed."
    )

    print(
        "=" * 100
    )

    print()

    print(
        "STAGE 11 COMPLETE"
    )

    print(
        "=" * 100
    )


# ============================================================
# START
# ============================================================

if __name__ == "__main__":

    main()